spring:
  application:
    name: ms-loan

  kafka:
    bootstrap-servers:
      - localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5433/loan_db
    username: admin
    password: password

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
